# Generated by Django 5.1.15 on 2026-10-01 16:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texttoimagemodelconfig',
            options={'ordering': ['sort_order', '-is_default', 'name'], 'verbose_name': 'نموذج تحويل النص إلى صور (T2I Model)', 'verbose_name_plural': 'نماذج تحويل النص إلى صور (T2I Models)'},
        ),
        migrations.AlterModelOptions(
            name='texttoimagesetting',
            options={'verbose_name': 'إعدادات عامة لتحويل النص إلى صور', 'verbose_name_plural': 'إعدادات عامة لتحويل النص إلى صور'},
        ),
        migrations.RemoveField(
            model_name='texttoimagemodelconfig',
            name='cost_per_image',
        ),
        migrations.AddField(
            model_name='texttoimagemodelconfig',
            name='cost_1k',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='الكريديت المطلوب لتوليد صورة واحدة بدقة 1K (1024px)', max_digits=10, verbose_name='سعر دقة 1K (Standard)'),
        ),
        migrations.AddField(
            model_name='texttoimagemodelconfig',
            name='cost_2k',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='الكريديت المطلوب لتوليد صورة واحدة بدقة 2K (2048px)', max_digits=10, verbose_name='سعر دقة 2K (HD)'),
        ),
        migrations.AddField(
            model_name='texttoimagemodelconfig',
            name='cost_4k',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='الكريديت المطلوب لتوليد صورة واحدة بدقة 4K (4096px)', max_digits=10, verbose_name='سعر دقة 4K (Ultra)'),
        ),
        migrations.AddField(
            model_name='texttoimagemodelconfig',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AddField(
            model_name='texttoimagemodelconfig',
            name='supported_resolutions',
            field=models.CharField(default='1k,2k,4k', help_text='الجودات المدعومة مفصولة بفاصلة مثل: 1k,2k,4k', max_length=100, verbose_name='الجودات المدعومة'),
        ),
        migrations.AddField(
            model_name='texttoimagesetting',
            name='max_prompt_length',
            field=models.IntegerField(default=1000, verbose_name='الحد الأقصى لطول الوصف (Prompt)'),
        ),
        migrations.AlterField(
            model_name='texttoimagemodelconfig',
            name='allowed_wallet',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة المسموحة'),
        ),
        migrations.AlterField(
            model_name='texttoimagemodelconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل للاستخدام'),
        ),
        migrations.AlterField(
            model_name='texttoimagemodelconfig',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='النموذج الافتراضي'),
        ),
        migrations.AlterField(
            model_name='texttoimagemodelconfig',
            name='model_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='معرف النموذج (Model ID)'),
        ),
        migrations.AlterField(
            model_name='texttoimagemodelconfig',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم النموذج'),
        ),
        migrations.AlterField(
            model_name='texttoimagemodelconfig',
            name='provider',
            field=models.CharField(default='Crun AI', max_length=50, verbose_name='المزود'),
        ),
        migrations.AlterField(
            model_name='texttoimagesetting',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الأداة عموماً'),
        ),
        migrations.AlterField(
            model_name='texttoimagesetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='وضع الصيانة'),
        ),
    ]
