# Generated by Django 5.1.15 on 2026-10-01 04:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtsModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(default='Gemini', max_length=50)),
                ('cost_per_char', models.DecimalField(decimal_places=5, default=Decimal('0.00100'), max_digits=10)),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='standard', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'TTS Model Config',
                'verbose_name_plural': 'TTS Model Configs',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TtsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('max_chars', models.IntegerField(default=5000)),
            ],
            options={
                'verbose_name': 'TTS General Setting',
                'verbose_name_plural': 'TTS General Settings',
            },
        ),
        migrations.CreateModel(
            name='TtsVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('display_name_ar', models.CharField(max_length=100)),
                ('language_code', models.CharField(default='ar-XA', max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('provider', models.CharField(default='Gemini', max_length=50)),
                ('preview_audio_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TTS Voice',
                'verbose_name_plural': 'TTS Voices',
                'ordering': ['language_code', 'display_name'],
            },
        ),
    ]
