# Generated by Django 5.1.15 on 2026-10-01 17:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttsmodelconfig',
            options={'ordering': ['sort_order', '-is_default', 'name'], 'verbose_name': 'إعدادات نموذج الصوت (Google Gemini TTS)', 'verbose_name_plural': 'نماذج الصوت (TTS Models)'},
        ),
        migrations.AlterModelOptions(
            name='ttssetting',
            options={'verbose_name': 'الإعدادات العامة لأداة تحويل النص إلى صوت', 'verbose_name_plural': 'الإعدادات العامة لأداة تحويل النص إلى صوت'},
        ),
        migrations.AlterModelOptions(
            name='ttsvoice',
            options={'ordering': ['sort_order', 'display_name_ar'], 'verbose_name': 'شخصية ونبرة صوتية (TTS Voice Profile)', 'verbose_name_plural': 'بروفايلات الأصوات (TTS Voices)'},
        ),
        migrations.AddField(
            model_name='ttsmodelconfig',
            name='chars_per_block',
            field=models.IntegerField(default=500, help_text='عدد الحروف المكونة للبلوك الواحد للتسعير (افتراضياً 500 حرف)', verbose_name='عدد الحروف في كل بلوك (Chars Per Block)'),
        ),
        migrations.AddField(
            model_name='ttsmodelconfig',
            name='cost_per_block_high',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='تكلفة البلوك الواحد عند اختيار الجودة الفائقة (High Quality Studio)', max_digits=10, verbose_name='سعر البلوك للجودة العالية (رصيد/بلوك)'),
        ),
        migrations.AddField(
            model_name='ttsmodelconfig',
            name='cost_per_block_standard',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.5000'), help_text='تكلفة البلوك الواحد عند اختيار الجودة العادية (Normal Quality)', max_digits=10, verbose_name='سعر البلوك للجودة العادية (رصيد/بلوك)'),
        ),
        migrations.AddField(
            model_name='ttsmodelconfig',
            name='quality_tier',
            field=models.CharField(choices=[('standard', 'جودة قياسية (Standard Quality)'), ('high', 'جودة فائقة سينمائية (High Quality Studio)')], default='standard', help_text='المستوى الجودوي الأساسي للنموذج: قياسي أو فائق', max_length=20, verbose_name='مستوى الجودة للنموذج'),
        ),
        migrations.AddField(
            model_name='ttsmodelconfig',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='ترتيب النموذج في القوائم المنسدلة', verbose_name='ترتيب الظهور'),
        ),
        migrations.AddField(
            model_name='ttsvoice',
            name='accent_note',
            field=models.CharField(blank=True, help_text='وصف النبرة وطبيعة الأداء', max_length=255, verbose_name='وصف النبرة التعبيرية'),
        ),
        migrations.AddField(
            model_name='ttsvoice',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='ترتيب الظهور'),
        ),
        migrations.AddField(
            model_name='ttsvoice',
            name='voice_category',
            field=models.CharField(choices=[('formal', 'رسمي وإخباري (Formal & News)'), ('warm', 'ودود ودافئ (Warm & Conversational)'), ('dynamic', 'حماسي وإعلاني (Commercial & Energetic)'), ('dramatic', 'درامي وسينمائي (Dramatic & Cinematic)'), ('storytelling', 'سرد قصصي (Storytelling & Audiobooks)'), ('educational', 'تعليمي وأكاديمي (Educational & Explainer)'), ('luxury', 'فخامة وبرستيج (Luxury & Prestige)')], default='formal', max_length=30, verbose_name='تصنيف الصوت وأسلوبه'),
        ),
        migrations.AlterField(
            model_name='ttsmodelconfig',
            name='allowed_wallet',
            field=models.CharField(choices=[('standard', 'الرصيد الأساسي (Standard)'), ('premium', 'الرصيد المميز (Premium)'), ('both', 'المحفظتان معاً (Both)')], default='both', help_text='نوع الرصيد المسموح بالخصم منه لهذا النموذج', max_length=20, verbose_name='المحفظة المسموحة'),
        ),
        migrations.AlterField(
            model_name='ttsmodelconfig',
            name='cost_per_char',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00100'), help_text='تستخدم كاحتياط عند عدم الاعتماد على البلوكات', max_digits=10, verbose_name='تكلفة الحرف الواحد (احتياط)'),
        ),
        migrations.AlterField(
            model_name='ttsmodelconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='إتاحة النموذج للمستخدمين في واجهة الاستوديو', verbose_name='مفعل في الاستوديو'),
        ),
        migrations.AlterField(
            model_name='ttsmodelconfig',
            name='is_default',
            field=models.BooleanField(default=False, help_text='النموذج المختار تلقائياً عند فتح الأداة', verbose_name='نموذج افتراضي'),
        ),
        migrations.AlterField(
            model_name='ttsmodelconfig',
            name='model_id',
            field=models.CharField(help_text='المعرف التقني للنموذج في Google Gemini (مثل gemini-2.5-pro-tts)', max_length=100, unique=True, verbose_name='معرف النموذج البرمجي (Model ID)'),
        ),
        migrations.AlterField(
            model_name='ttsmodelconfig',
            name='name',
            field=models.CharField(help_text='اسم النموذج الرسمي النظيف كما يظهر في واجهة الاستوديو بدون ذكر المزودات', max_length=150, verbose_name='اسم النموذج الظاهر للمستخدم'),
        ),
        migrations.AlterField(
            model_name='ttsmodelconfig',
            name='provider',
            field=models.CharField(default='Google Gemini', help_text='مزود الخدمة الأساسي (Google Gemini)', max_length=50, verbose_name='المزود'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الأداة'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='وضع الصيانة'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='max_chars',
            field=models.IntegerField(default=10000, verbose_name='الحد الأقصى لعدد الحروف في الطلب'),
        ),
        migrations.AlterField(
            model_name='ttsvoice',
            name='display_name',
            field=models.CharField(help_text='اسم الشخصية الإذاعية بالإنجليزية', max_length=100, verbose_name='الاسم بالإنجليزية (Persona Name EN)'),
        ),
        migrations.AlterField(
            model_name='ttsvoice',
            name='display_name_ar',
            field=models.CharField(help_text='اسم الشخصية الإذاعية بالعربية بدون ذكر المصدر', max_length=100, verbose_name='الاسم بالعربية (Persona Name AR)'),
        ),
        migrations.AlterField(
            model_name='ttsvoice',
            name='gender',
            field=models.CharField(choices=[('Male', 'ذكر (Male)'), ('Female', 'أنثى (Female)')], default='Male', max_length=20, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='ttsvoice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='ttsvoice',
            name='language_code',
            field=models.CharField(default='multilingual', max_length=20, verbose_name='رمز اللغة'),
        ),
        migrations.AlterField(
            model_name='ttsvoice',
            name='preview_audio_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='رابط عينة الصوت'),
        ),
        migrations.AlterField(
            model_name='ttsvoice',
            name='provider',
            field=models.CharField(default='Google Gemini', max_length=50, verbose_name='المزود'),
        ),
        migrations.AlterField(
            model_name='ttsvoice',
            name='voice_id',
            field=models.CharField(help_text='معرف الصوت في Google Gemini Live/TTS (مثل Kore, Puck, Charon, Fenrir...)', max_length=100, unique=True, verbose_name='معرف الصوت التقني (Voice ID)'),
        ),
    ]
