# Generated by Django 5.1.15 on 2026-10-01 04:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SttModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(default='Whisper', max_length=50)),
                ('cost_per_second', models.DecimalField(decimal_places=4, default=Decimal('0.0167'), max_digits=10)),
                ('cost_per_minute', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10)),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='standard', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'STT Model Config',
                'verbose_name_plural': 'STT Model Configs',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SttSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('max_file_size_mb', models.IntegerField(default=25)),
                ('max_duration_minutes', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'STT General Setting',
                'verbose_name_plural': 'STT General Settings',
            },
        ),
    ]
