# Generated by Django 5.1.15 on 2026-10-01 16:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sttmodelconfig',
            options={'ordering': ['sort_order', '-is_default', 'name'], 'verbose_name': 'إعدادات نموذج تفريغ الصوت (OpenAI Whisper)', 'verbose_name_plural': 'نماذج تفريغ الصوت (STT Models)'},
        ),
        migrations.AlterModelOptions(
            name='sttsetting',
            options={'verbose_name': 'الإعدادات العامة لأداة تفريغ الصوت', 'verbose_name_plural': 'الإعدادات العامة لأداة تفريغ الصوت'},
        ),
        migrations.AddField(
            model_name='sttmodelconfig',
            name='max_duration_seconds',
            field=models.IntegerField(default=3600, help_text='أقصى مدة صوتية مسموحة بالثواني (افتراضياً 3600 ثانية = 60 دقيقة)', verbose_name='الحد الأقصى للمدة (ثواني)'),
        ),
        migrations.AddField(
            model_name='sttmodelconfig',
            name='min_duration_seconds',
            field=models.IntegerField(default=1, help_text='أقل مدة صوتية مسموحة بالثواني', verbose_name='الحد الأدنى للمدة (ثواني)'),
        ),
        migrations.AddField(
            model_name='sttmodelconfig',
            name='pricing_type',
            field=models.CharField(choices=[('per_minute', 'حسب الدقيقة المحسوبة بالثواني (Per Minute)'), ('flat', 'سعر ثابت مقطوع لكل ملف (Flat Rate)')], default='per_minute', help_text='طريقة احتساب التكلفة: بالدقيقة أو سعر ثابت', max_length=20, verbose_name='آلية التسعير'),
        ),
        migrations.AddField(
            model_name='sttmodelconfig',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='ترتيب النموذج في القوائم المنسدلة', verbose_name='ترتيب الظهور'),
        ),
        migrations.AlterField(
            model_name='sttmodelconfig',
            name='allowed_wallet',
            field=models.CharField(choices=[('standard', 'الرصيد الأساسي (Standard)'), ('premium', 'الرصيد المميز (Premium)'), ('both', 'المحفظتان معاً (Both)')], default='standard', help_text='نوع الرصيد المسموح بالخصم منه لهذا النموذج', max_length=20, verbose_name='المحفظة المسموحة'),
        ),
        migrations.AlterField(
            model_name='sttmodelconfig',
            name='cost_per_minute',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='تكلفة التفريغ الصوتي لكل دقيقة كاملة', max_digits=10, verbose_name='سعر الدقيقة (رصيد/دقيقة)'),
        ),
        migrations.AlterField(
            model_name='sttmodelconfig',
            name='cost_per_second',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0167'), help_text='تكلفة الثانية (تُحسب تلقائياً أو تُحدد كحد أدنى للثواني)', max_digits=10, verbose_name='سعر الثانية (رصيد/ثانية)'),
        ),
        migrations.AlterField(
            model_name='sttmodelconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='إتاحة النموذج للمستخدمين في واجهة الاستوديو', verbose_name='مفعل في الاستوديو'),
        ),
        migrations.AlterField(
            model_name='sttmodelconfig',
            name='is_default',
            field=models.BooleanField(default=False, help_text='النموذج المختار تلقائياً عند فتح الأداة', verbose_name='نموذج افتراضي'),
        ),
        migrations.AlterField(
            model_name='sttmodelconfig',
            name='model_id',
            field=models.CharField(help_text='المعرف التقني للنموذج في OpenAI (مثل whisper-1)', max_length=100, unique=True, verbose_name='معرف النموذج البرمجي (Model ID)'),
        ),
        migrations.AlterField(
            model_name='sttmodelconfig',
            name='name',
            field=models.CharField(help_text='اسم النموذج الرسمي كما يظهر في واجهة الاستوديو بدون ذكر المزودات', max_length=150, verbose_name='اسم النموذج الظاهر للمستخدم'),
        ),
        migrations.AlterField(
            model_name='sttmodelconfig',
            name='provider',
            field=models.CharField(default='OpenAI', help_text='مزود الخدمة الأساسي (OpenAI)', max_length=50, verbose_name='المزود'),
        ),
        migrations.AlterField(
            model_name='sttsetting',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الأداة'),
        ),
        migrations.AlterField(
            model_name='sttsetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='وضع الصيانة'),
        ),
        migrations.AlterField(
            model_name='sttsetting',
            name='max_duration_minutes',
            field=models.IntegerField(default=30, verbose_name='أقصى مدة تسجيل (دقائق)'),
        ),
        migrations.AlterField(
            model_name='sttsetting',
            name='max_file_size_mb',
            field=models.IntegerField(default=50, verbose_name='أقصى حجم ملف صوتي (ميغابايت)'),
        ),
    ]
