# Generated by Django 5.1.15 on 2026-10-01 16:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_to_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencetovideomodelconfig',
            options={'ordering': ['sort_order', '-is_default', 'name'], 'verbose_name': 'نموذج الفيديو المرجعي (R2V Model)', 'verbose_name_plural': 'نماذج الفيديو المرجعي (R2V Models)'},
        ),
        migrations.AlterModelOptions(
            name='referencetovideosetting',
            options={'verbose_name': 'إعدادات عامة للفيديو المرجعي', 'verbose_name_plural': 'إعدادات عامة للفيديو المرجعي'},
        ),
        migrations.RemoveField(
            model_name='referencetovideomodelconfig',
            name='cost_per_generation',
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='accepts_audio_ref',
            field=models.BooleanField(default=False, help_text='يدعم رفع مسار صوتي أو موسيقي لمزامنة المشهد وتوقيت الحركة معه.', verbose_name='دعم الصوت المرجعي (Audio Reference / Sync)'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='accepts_image_ref',
            field=models.BooleanField(default=True, help_text='يدعم رفع صور للشخصية أو النمط أو الزي.', verbose_name='دعم مراجع الصور (Image Reference)'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='accepts_video_ref',
            field=models.BooleanField(default=False, help_text='يدعم رفع مقطع فيديو لاستخراج ونقل الحركة وتوجيه الكاميرا.', verbose_name='دعم فيديو الحركة المرجعي (Video / Motion Reference)'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='allowed_durations',
            field=models.CharField(default='5,10', help_text='المدد المسموحة مفصولة بفاصلة (مثال: 5,10) أو نطاق مرن (مثال: 4-15)', max_length=100, verbose_name='المدد الزمنية المتاحة (ثوانٍ)'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='cost_1080p',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='الكريديت المطلوب لكل ثانية أو للعملية الواحدة لدقة 1080p', max_digits=10, verbose_name='سعر 1080p'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='cost_480p',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='الكريديت المطلوب لكل ثانية أو للعملية الواحدة لدقة 480p', max_digits=10, verbose_name='سعر 480p'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='cost_4k',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='الكريديت المطلوب لكل ثانية أو للعملية الواحدة لدقة 4K', max_digits=10, verbose_name='سعر 4K'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='cost_720p',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='الكريديت المطلوب لكل ثانية أو للعملية الواحدة لدقة 720p', max_digits=10, verbose_name='سعر 720p'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='default_duration',
            field=models.IntegerField(default=5, verbose_name='المدة الافتراضية (ثوانٍ)'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='duration_type',
            field=models.CharField(choices=[('discrete', 'مدد محددة (Discrete)'), ('range', 'نطاق مرن (Range)')], default='discrete', max_length=20, verbose_name='نوع المدة الزمنية'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='max_audio_refs',
            field=models.IntegerField(default=1, verbose_name='الحد الأقصى للملفات الصوتية المرجعية'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='max_image_refs',
            field=models.IntegerField(default=3, verbose_name='الحد الأقصى لصور المراجع'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='max_video_refs',
            field=models.IntegerField(default=1, verbose_name='الحد الأقصى لمقاطع الفيديو المرجعية'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='pricing_type',
            field=models.CharField(choices=[('per_second', 'بالثانية (Per Second)'), ('per_request', 'بالعملية/الريكوست (Per Request)')], default='per_second', max_length=20, verbose_name='طريقة التسعير'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AddField(
            model_name='referencetovideomodelconfig',
            name='supported_resolutions',
            field=models.CharField(default='720p,1080p', help_text='الجودات المدعومة مفصولة بفاصلة مثل: 480p,720p,1080p,4k', max_length=100, verbose_name='الجودات المدعومة'),
        ),
        migrations.AddField(
            model_name='referencetovideosetting',
            name='max_file_size_mb',
            field=models.IntegerField(default=50, verbose_name='الحد الأقصى لحجم الملفات المرفوعة (MB)'),
        ),
        migrations.AlterField(
            model_name='referencetovideomodelconfig',
            name='allowed_wallet',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة المسموحة'),
        ),
        migrations.AlterField(
            model_name='referencetovideomodelconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل للاستخدام'),
        ),
        migrations.AlterField(
            model_name='referencetovideomodelconfig',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='النموذج الافتراضي'),
        ),
        migrations.AlterField(
            model_name='referencetovideomodelconfig',
            name='model_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='معرف النموذج (Model ID)'),
        ),
        migrations.AlterField(
            model_name='referencetovideomodelconfig',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم النموذج'),
        ),
        migrations.AlterField(
            model_name='referencetovideomodelconfig',
            name='provider',
            field=models.CharField(default='Crun AI', max_length=50, verbose_name='المزود'),
        ),
        migrations.AlterField(
            model_name='referencetovideosetting',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الأداة عموماً'),
        ),
        migrations.AlterField(
            model_name='referencetovideosetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='وضع الصيانة'),
        ),
        migrations.AlterField(
            model_name='referencetovideosetting',
            name='max_reference_images',
            field=models.IntegerField(default=20, verbose_name='الحد الأقصى للصور المرجعية'),
        ),
    ]
