# Generated by Django 5.1.15 on 2026-10-01 04:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_details', models.TextField(help_text='Bank Account, IBAN, InstaPay, Vodafone Cash, etc.')),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Manual Payment Method',
                'verbose_name_plural': 'Manual Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='paymob, paypal', max_length=50, unique=True)),
                ('public_key', models.CharField(blank=True, max_length=500, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=500, null=True)),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Additional JSON options')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway Config',
                'verbose_name_plural': 'Payment Gateway Configs',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('features_ar', models.TextField(blank=True, null=True)),
                ('duration_days', models.IntegerField(default=30)),
                ('grace_period_days', models.IntegerField(default=3)),
                ('price_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price_egp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_percentage_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_percentage_egp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('fixed_fee_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fixed_fee_egp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('standard_credits', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('premium_credits', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('text_to_image_enabled', models.BooleanField(default=True)),
                ('text_to_video_enabled', models.BooleanField(default=True)),
                ('image_to_video_enabled', models.BooleanField(default=True)),
                ('reference_to_video_enabled', models.BooleanField(default=True)),
                ('lipsync_enabled', models.BooleanField(default=True)),
                ('motion_control_enabled', models.BooleanField(default=True)),
                ('stt_enabled', models.BooleanField(default=True)),
                ('tts_enabled', models.BooleanField(default=True)),
                ('avatar_video_enabled', models.BooleanField(default=True)),
                ('is_free_trial', models.BooleanField(default=False)),
                ('allowed_voices', models.TextField(blank=True, help_text='Comma-separated voice names', null=True)),
                ('is_default_registration_plan', models.BooleanField(default=False)),
                ('affiliate_first_commission_type', models.CharField(default='Percentage', max_length=50)),
                ('affiliate_first_commission_value_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('affiliate_first_commission_value_egp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('affiliate_recurring_commission_type', models.CharField(default='Percentage', max_length=50)),
                ('affiliate_recurring_commission_value_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('affiliate_recurring_commission_value_egp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price_usd', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, help_text='External Transaction ID', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(help_text='paymob, paypal, manual, admin_grant', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=30)),
                ('receipt_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.plan')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('pdf_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='billing.payment')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('freeze', 'Freeze'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.subscription'),
        ),
    ]
