# Generated by Django 5.1.15 on 2026-10-01 05:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribution_period_days', models.PositiveIntegerField(default=30, help_text='Cookie / referral attribution window in days')),
                ('hold_period_days', models.PositiveIntegerField(default=14, help_text='Days to hold commission before becoming available for withdrawal')),
                ('first_purchase_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Commission % for first purchase', max_digits=5)),
                ('recurring_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Commission % for recurring purchases', max_digits=5)),
                ('max_package_duration_days', models.PositiveIntegerField(default=365, help_text='Cap on cumulative subscription days eligible for commission')),
                ('min_payout_usd', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('min_payout_egp', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('is_program_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Affiliate Setting',
                'verbose_name_plural': 'Affiliate Settings',
            },
        ),
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('referral_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('mobile_number', models.CharField(blank=True, max_length=30)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('facebook_account', models.CharField(blank=True, max_length=200)),
                ('policy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate Profile',
                'verbose_name_plural': 'Affiliate Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliatePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payout_method', models.CharField(help_text='e.g. Vodafone Cash, Instapay, Bank Transfer, PayPal', max_length=100)),
                ('payout_account', models.CharField(help_text='Account details, phone number, IBAN or PayPal email', max_length=300)),
                ('affiliate_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing Payment'), ('PAID', 'Paid & Completed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('transfer_receipt_url', models.URLField(blank=True, help_text='Receipt URL / Proof of transfer', max_length=1000, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='affiliate.affiliateprofile')),
            ],
            options={
                'verbose_name': 'Affiliate Payout',
                'verbose_name_plural': 'Affiliate Payouts',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attribution_expires_at', models.DateTimeField()),
                ('has_converted', models.BooleanField(default=False)),
                ('first_eligible_payment_at', models.DateTimeField(blank=True, null=True)),
                ('accumulated_package_days', models.PositiveIntegerField(default=0)),
                ('affiliate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='affiliate.affiliateprofile')),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate Referral',
                'verbose_name_plural': 'Affiliate Referrals',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FIRST_PURCHASE', 'First Purchase'), ('RECURRING', 'Recurring'), ('REVERSAL', 'Reversal')], default='FIRST_PURCHASE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Applied percentage rate', max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Hold Period)'), ('AVAILABLE', 'Available for Payout'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed (Refunded)'), ('PAID', 'Paid Out')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_at', models.DateTimeField(help_text='Release date after hold period')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions_generated', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.payment')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.plan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscription')),
                ('affiliate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='affiliate.affiliateprofile')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='affiliate.affiliatereferral')),
            ],
            options={
                'verbose_name': 'Affiliate Commission',
                'verbose_name_plural': 'Affiliate Commissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
