from decimal import Decimal
from django.core.management.base import BaseCommand
from apps.tools.lipsync.models import LipSyncModelConfig, LipSyncSetting


class Command(BaseCommand):
    help = 'Seeds all 26 official Crun AI LipSync models with exact media targets, durations, and locked settings.'

    def handle(self, *args, **options):
        models_data = [
            {
                'name': 'AI LipSync Pro (Universal Face & Video)',
                'model_id': 'crun-lipsync-pro',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-60',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.50'),
                'cost_4k': Decimal('6.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': True,
                'sort_order': 1,
            },
            {
                'name': 'Kling 4.0 LipSync Cinematic',
                'model_id': 'kling-4-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-30',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.00'),
                'cost_1080p': Decimal('6.00'),
                'cost_4k': Decimal('10.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 2,
            },
            {
                'name': 'Kling 3.0 LipSync Pro',
                'model_id': 'kling-3-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-30',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('5.00'),
                'cost_4k': Decimal('8.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 3,
            },
            {
                'name': 'Kling 2.6 Native Audio & Dialogue',
                'model_id': 'kling-2-6-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-20',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.25'),
                'cost_720p': Decimal('2.50'),
                'cost_1080p': Decimal('4.00'),
                'cost_4k': Decimal('7.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 4,
            },
            {
                'name': 'Kling 2.5 Turbo Speech Sync',
                'model_id': 'kling-2-5-turbo-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.50'),
                'cost_4k': Decimal('6.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 5,
            },
            {
                'name': 'Google Veo 3.1 LipSync Studio',
                'model_id': 'veo-3-1-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'discrete',
                'allowed_durations': '4,6,8,12',
                'default_duration': 4,
                'supported_resolutions': '720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.00'),
                'cost_1080p': Decimal('6.50'),
                'cost_4k': Decimal('11.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 6,
            },
            {
                'name': 'Google Veo 2 Audio-Visual Sync',
                'model_id': 'veo-2-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'discrete',
                'allowed_durations': '4,6,8',
                'default_duration': 4,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('5.00'),
                'cost_4k': Decimal('8.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 7,
            },
            {
                'name': 'Sora 2 LipSync Pro',
                'model_id': 'sora-2-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-25',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.00'),
                'cost_1080p': Decimal('6.50'),
                'cost_4k': Decimal('11.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 8,
            },
            {
                'name': 'Sora 2 Fast Speech Sync',
                'model_id': 'sora-2-fast-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-15',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('5.00'),
                'cost_4k': Decimal('8.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 9,
            },
            {
                'name': 'Grok Imagine Video 1.5 LipSync',
                'model_id': 'grok-imagine-1-5-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-20',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.50'),
                'cost_4k': Decimal('6.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 10,
            },
            {
                'name': 'Grok Imagine Dialogue Sync',
                'model_id': 'grok-imagine-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.00'),
                'cost_4k': Decimal('5.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 11,
            },
            {
                'name': 'HappyHorse 1.1 LipSync',
                'model_id': 'happyhorse-1-1-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-20',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.00'),
                'cost_4k': Decimal('5.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 12,
            },
            {
                'name': 'HappyHorse 1.0 Fast Sync',
                'model_id': 'happyhorse-1-0-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-15',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('0.75'),
                'cost_720p': Decimal('1.50'),
                'cost_1080p': Decimal('2.50'),
                'cost_4k': Decimal('4.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 13,
            },
            {
                'name': 'Wan 3.0 Audio-Visual Dialogue',
                'model_id': 'wan-3-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-25',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('5.00'),
                'cost_4k': Decimal('8.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 14,
            },
            {
                'name': 'Wan 2.7 Multilingual Speech Sync',
                'model_id': 'wan-2-7-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-20',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.25'),
                'cost_720p': Decimal('2.50'),
                'cost_1080p': Decimal('4.00'),
                'cost_4k': Decimal('7.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 15,
            },
            {
                'name': 'Wan 2.5 Preview Speech-to-Face',
                'model_id': 'wan-2-5-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.50'),
                'cost_4k': Decimal('6.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 16,
            },
            {
                'name': 'Wan 2.2 Animate LipSync',
                'model_id': 'wan-2-2-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.50'),
                'cost_4k': Decimal('6.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 17,
            },
            {
                'name': 'Vidu Q3 Ultra Native Audio Sync',
                'model_id': 'vidu-q3-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-30',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('5.00'),
                'cost_4k': Decimal('8.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 18,
            },
            {
                'name': 'Vidu Q2 LipSync Fast',
                'model_id': 'vidu-q2-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-20',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.50'),
                'cost_4k': Decimal('6.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 19,
            },
            {
                'name': 'Runway Gen-4 Aleph Speech Sync',
                'model_id': 'gen-4-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-20',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.00'),
                'cost_1080p': Decimal('6.50'),
                'cost_4k': Decimal('11.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 20,
            },
            {
                'name': 'Seedance 2.5 Audio-Synchronized Video',
                'model_id': 'seedance-2-5-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-25',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('5.00'),
                'cost_4k': Decimal('8.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 21,
            },
            {
                'name': 'Seedance 2.0 Dialogue Pro',
                'model_id': 'seedance-2-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-20',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.25'),
                'cost_720p': Decimal('2.50'),
                'cost_1080p': Decimal('4.50'),
                'cost_4k': Decimal('7.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 22,
            },
            {
                'name': 'MiniMax H3 Speech-to-Motion',
                'model_id': 'minimax-h3-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-20',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.25'),
                'cost_720p': Decimal('2.50'),
                'cost_1080p': Decimal('4.00'),
                'cost_4k': Decimal('7.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 23,
            },
            {
                'name': 'PixVerse V6 Character Speech',
                'model_id': 'pixverse-v6-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-15',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.50'),
                'cost_4k': Decimal('6.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 24,
            },
            {
                'name': 'Hailuo 2.3 Audio-Visual Sync',
                'model_id': 'hailuo-2-3-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-15',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.50'),
                'cost_4k': Decimal('6.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 25,
            },
            {
                'name': 'AI Avatar LipSync Studio',
                'model_id': 'ai-avatar-lipsync',
                'provider': 'Crun AI',
                'target_media_type': 'both',
                'duration_type': 'range',
                'allowed_durations': '3-60',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.50'),
                'cost_4k': Decimal('6.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 26,
            },
        ]

        count = 0
        for m in models_data:
            existing = LipSyncModelConfig.objects.filter(model_id=m['model_id']).first()
            if existing:
                LipSyncModelConfig.objects.filter(pk=existing.pk).update(**m)
            else:
                LipSyncModelConfig.objects.create(**m)
            count += 1

        setting, _ = LipSyncSetting.objects.get_or_create(id=1)
        setting.is_enabled = True
        setting.maintenance_mode = False
        setting.max_video_size_mb = 100
        setting.max_audio_size_mb = 35
        setting.max_duration_seconds = 60
        setting.save()

        self.stdout.write(self.style.SUCCESS(f"Successfully seeded {count} official Crun AI LipSync models with exact media targets and locked settings!"))
