# Generated by Django 5.1.15 on 2026-10-01 16:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipsync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lipsyncmodelconfig',
            options={'ordering': ['sort_order', '-is_default', 'name'], 'verbose_name': 'نموذج مزامنة حركة الشفاه (LipSync Model)', 'verbose_name_plural': 'نماذج مزامنة حركة الشفاه (LipSync Models)'},
        ),
        migrations.AlterModelOptions(
            name='lipsyncsetting',
            options={'verbose_name': 'إعدادات عامة لمزامنة حركة الشفاه', 'verbose_name_plural': 'إعدادات عامة لمزامنة حركة الشفاه'},
        ),
        migrations.RemoveField(
            model_name='lipsyncmodelconfig',
            name='cost_per_second',
        ),
        migrations.AddField(
            model_name='lipsyncmodelconfig',
            name='allowed_durations',
            field=models.CharField(default='5,10', help_text='المدد المسموحة مفصولة بفاصلة (مثال: 5,10) أو نطاق مرن (مثال: 3-30)', max_length=100, verbose_name='المدد الزمنية المتاحة (ثوانٍ)'),
        ),
        migrations.AddField(
            model_name='lipsyncmodelconfig',
            name='cost_1080p',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.50'), help_text='الكريديت المطلوب لكل ثانية أو للعملية الواحدة لدقة 1080p', max_digits=10, verbose_name='سعر 1080p'),
        ),
        migrations.AddField(
            model_name='lipsyncmodelconfig',
            name='cost_480p',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='الكريديت المطلوب لكل ثانية أو للعملية الواحدة لدقة 480p', max_digits=10, verbose_name='سعر 480p'),
        ),
        migrations.AddField(
            model_name='lipsyncmodelconfig',
            name='cost_4k',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='الكريديت المطلوب لكل ثانية أو للعملية الواحدة لدقة 4K', max_digits=10, verbose_name='سعر 4K'),
        ),
        migrations.AddField(
            model_name='lipsyncmodelconfig',
            name='cost_720p',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='الكريديت المطلوب لكل ثانية أو للعملية الواحدة لدقة 720p', max_digits=10, verbose_name='سعر 720p'),
        ),
        migrations.AddField(
            model_name='lipsyncmodelconfig',
            name='default_duration',
            field=models.IntegerField(default=5, verbose_name='المدة الافتراضية (ثوانٍ)'),
        ),
        migrations.AddField(
            model_name='lipsyncmodelconfig',
            name='duration_type',
            field=models.CharField(choices=[('discrete', 'مدد محددة (Discrete)'), ('range', 'نطاق مرن (Range)')], default='discrete', max_length=20, verbose_name='نوع المدة الزمنية'),
        ),
        migrations.AddField(
            model_name='lipsyncmodelconfig',
            name='pricing_type',
            field=models.CharField(choices=[('per_second', 'بالثانية (Per Second)'), ('per_request', 'بالعملية/الريكوست (Per Request)')], default='per_second', max_length=20, verbose_name='طريقة التسعير'),
        ),
        migrations.AddField(
            model_name='lipsyncmodelconfig',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AddField(
            model_name='lipsyncmodelconfig',
            name='supported_resolutions',
            field=models.CharField(default='480p,720p,1080p', help_text='الجودات المدعومة مفصولة بفاصلة مثل: 480p,720p,1080p,4k', max_length=100, verbose_name='الجودات المدعومة'),
        ),
        migrations.AddField(
            model_name='lipsyncmodelconfig',
            name='target_media_type',
            field=models.CharField(choices=[('both', 'فيديو أو صورة ثابتة (Both)'), ('video_only', 'فيديو فقط (Video Only)'), ('image_only', 'صورة وجه فقط (Image Only)')], default='both', max_length=20, verbose_name='نوع الوسائط المدعومة للوجه'),
        ),
        migrations.AlterField(
            model_name='lipsyncmodelconfig',
            name='allowed_wallet',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة المسموحة'),
        ),
        migrations.AlterField(
            model_name='lipsyncmodelconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل للاستخدام'),
        ),
        migrations.AlterField(
            model_name='lipsyncmodelconfig',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='النموذج الافتراضي'),
        ),
        migrations.AlterField(
            model_name='lipsyncmodelconfig',
            name='model_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='معرف النموذج (Model ID)'),
        ),
        migrations.AlterField(
            model_name='lipsyncmodelconfig',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم النموذج'),
        ),
        migrations.AlterField(
            model_name='lipsyncmodelconfig',
            name='provider',
            field=models.CharField(default='Crun AI', max_length=50, verbose_name='المزود'),
        ),
        migrations.AlterField(
            model_name='lipsyncsetting',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الأداة عموماً'),
        ),
        migrations.AlterField(
            model_name='lipsyncsetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='وضع الصيانة'),
        ),
        migrations.AlterField(
            model_name='lipsyncsetting',
            name='max_audio_size_mb',
            field=models.IntegerField(default=25, verbose_name='الحد الأقصى لحجم الصوت (MB)'),
        ),
        migrations.AlterField(
            model_name='lipsyncsetting',
            name='max_duration_seconds',
            field=models.IntegerField(default=120, verbose_name='الحد الأقصى للمدة (ثوانٍ)'),
        ),
        migrations.AlterField(
            model_name='lipsyncsetting',
            name='max_video_size_mb',
            field=models.IntegerField(default=100, verbose_name='الحد الأقصى لحجم الفيديو (MB)'),
        ),
    ]
