# Generated by Django 5.1.15 on 2026-10-01 04:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextToVideoModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(default='Kling', max_length=50)),
                ('cost_480p', models.DecimalField(decimal_places=2, default=Decimal('2.40'), help_text='Credits per sec (480p)', max_digits=10)),
                ('cost_720p', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Credits per sec (720p)', max_digits=10)),
                ('cost_1080p', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Credits per sec (1080p)', max_digits=10)),
                ('cost_4k', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Credits per sec (4K)', max_digits=10)),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Text To Video Model Config',
                'verbose_name_plural': 'Text To Video Model Configs',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TextToVideoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('max_prompt_length', models.IntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'Text To Video General Setting',
                'verbose_name_plural': 'Text To Video General Settings',
            },
        ),
    ]
