from decimal import Decimal
from django.core.management.base import BaseCommand
from apps.tools.text_to_image.models import TextToImageModelConfig, TextToImageSetting


class Command(BaseCommand):
    help = 'Seeds all 25 official Crun AI Text-to-Image models with exact resolutions (1K, 2K, 4K) and locked attributes.'

    def handle(self, *args, **options):
        models_data = [
            {
                'name': 'Nano Banana 2',
                'model_id': 'nano-banana-2',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('2.00'),
                'cost_2k': Decimal('4.00'),
                'cost_4k': Decimal('8.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': True,
                'sort_order': 1,
            },
            {
                'name': 'Nano Banana Pro',
                'model_id': 'nano-banana-pro',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('3.00'),
                'cost_2k': Decimal('6.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 2,
            },
            {
                'name': 'Nano Banana 2 Lite',
                'model_id': 'nano-banana-2-lite',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('1.50'),
                'cost_2k': Decimal('3.00'),
                'cost_4k': Decimal('6.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 3,
            },
            {
                'name': 'Nano Banana Standard',
                'model_id': 'nano-banana',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('2.00'),
                'cost_2k': Decimal('4.00'),
                'cost_4k': Decimal('8.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 4,
            },
            {
                'name': 'Google Imagen 4',
                'model_id': 'imagen-4',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('3.00'),
                'cost_2k': Decimal('6.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 5,
            },
            {
                'name': 'Flux 2 Pro',
                'model_id': 'flux-2',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('3.50'),
                'cost_2k': Decimal('7.00'),
                'cost_4k': Decimal('14.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 6,
            },
            {
                'name': 'Flux 1.1 Pro',
                'model_id': 'flux-1-1',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('3.00'),
                'cost_2k': Decimal('6.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 7,
            },
            {
                'name': 'Flux Kontext',
                'model_id': 'flux-kontext',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('3.00'),
                'cost_2k': Decimal('6.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 8,
            },
            {
                'name': 'Seedream 5.0 Pro',
                'model_id': 'seedream-5-pro',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('3.50'),
                'cost_2k': Decimal('7.00'),
                'cost_4k': Decimal('14.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 9,
            },
            {
                'name': 'Seedream 5.0 Lite',
                'model_id': 'seedream-5',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('2.00'),
                'cost_2k': Decimal('4.00'),
                'cost_4k': Decimal('8.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 10,
            },
            {
                'name': 'Seedream 4.5',
                'model_id': 'seedream-4-5',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('2.50'),
                'cost_2k': Decimal('5.00'),
                'cost_4k': Decimal('10.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 11,
            },
            {
                'name': 'Seedream 4.0',
                'model_id': 'seedream-4',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('2.00'),
                'cost_2k': Decimal('4.00'),
                'cost_4k': Decimal('8.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 12,
            },
            {
                'name': 'GPT Image 2.5',
                'model_id': 'gpt-image-2-5',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('3.50'),
                'cost_2k': Decimal('7.00'),
                'cost_4k': Decimal('14.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 13,
            },
            {
                'name': 'GPT Image 2.0',
                'model_id': 'gpt-image-2',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('3.00'),
                'cost_2k': Decimal('6.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 14,
            },
            {
                'name': 'GPT Image 1.5',
                'model_id': 'gpt-image-1-5',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('2.50'),
                'cost_2k': Decimal('5.00'),
                'cost_4k': Decimal('10.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 15,
            },
            {
                'name': 'GPT Image 1.0',
                'model_id': 'gpt-image-1',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('2.00'),
                'cost_2k': Decimal('4.00'),
                'cost_4k': Decimal('8.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 16,
            },
            {
                'name': 'Grok Imagine Image 2.0',
                'model_id': 'grok-imagine-image-2',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('3.00'),
                'cost_2k': Decimal('6.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 17,
            },
            {
                'name': 'Grok Imagine Image',
                'model_id': 'grok-imagine',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('2.50'),
                'cost_2k': Decimal('5.00'),
                'cost_4k': Decimal('10.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 18,
            },
            {
                'name': 'Wan 2.7 Image Pro',
                'model_id': 'wan-2-7-image',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('3.00'),
                'cost_2k': Decimal('6.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 19,
            },
            {
                'name': 'Qwen Image 3.0',
                'model_id': 'qwen-image-3',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('3.00'),
                'cost_2k': Decimal('6.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 20,
            },
            {
                'name': 'Qwen Image 2.0',
                'model_id': 'qwen-image-2',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('2.50'),
                'cost_2k': Decimal('5.00'),
                'cost_4k': Decimal('10.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 21,
            },
            {
                'name': 'Qwen Image 1.0',
                'model_id': 'qwen-image',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('2.00'),
                'cost_2k': Decimal('4.00'),
                'cost_4k': Decimal('8.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 22,
            },
            {
                'name': 'Z-Image Turbo',
                'model_id': 'z-image-turbo',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('1.50'),
                'cost_2k': Decimal('3.00'),
                'cost_4k': Decimal('6.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 23,
            },
            {
                'name': 'Doubao Seed 2.1',
                'model_id': 'doubao-seed-2-1',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('2.50'),
                'cost_2k': Decimal('5.00'),
                'cost_4k': Decimal('10.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 24,
            },
            {
                'name': 'Doubao Seed 2.0',
                'model_id': 'doubao-seed-2',
                'provider': 'Crun AI',
                'supported_resolutions': '1k,2k,4k',
                'cost_1k': Decimal('2.00'),
                'cost_2k': Decimal('4.00'),
                'cost_4k': Decimal('8.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 25,
            },
        ]

        count = 0
        for m in models_data:
            existing = TextToImageModelConfig.objects.filter(model_id=m['model_id']).first()
            if existing:
                TextToImageModelConfig.objects.filter(pk=existing.pk).update(**m)
            else:
                TextToImageModelConfig.objects.create(**m)
            count += 1

        # General Setting
        setting, _ = TextToImageSetting.objects.get_or_create(id=1)
        setting.is_enabled = True
        setting.maintenance_mode = False
        setting.max_prompt_length = 1500
        setting.save()

        self.stdout.write(self.style.SUCCESS(f"Successfully seeded {count} official Crun AI Text-to-Image models with exact resolutions and locked settings!"))
