# Generated by Django 5.1.15 on 2026-10-01 04:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotionControlModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(default='Kling', max_length=50)),
                ('base_cost', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Flat cost per generation', max_digits=10)),
                ('cost_per_second', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=10)),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Motion Control Model Config',
                'verbose_name_plural': 'Motion Control Model Configs',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MotionControlSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Motion Control General Setting',
                'verbose_name_plural': 'Motion Control General Settings',
            },
        ),
    ]
