# Generated by Django 5.1.15 on 2026-10-01 16:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motioncontrolmodelconfig',
            options={'ordering': ['sort_order', '-is_default', 'name'], 'verbose_name': 'إعدادات نموذج التحكم الحركي (Crun AI)', 'verbose_name_plural': 'نماذج التحكم الحركي (Motion Control Models)'},
        ),
        migrations.AlterModelOptions(
            name='motioncontrolsetting',
            options={'verbose_name': 'الإعدادات العامة لأداة التحكم الحركي', 'verbose_name_plural': 'الإعدادات العامة لأداة التحكم الحركي'},
        ),
        migrations.AddField(
            model_name='motioncontrolmodelconfig',
            name='allowed_durations',
            field=models.JSONField(blank=True, help_text='قائمة بالمدد الثابتة إن كان النموذج لا يدعم سوى مدد معينة', null=True, verbose_name='المدد المحددة (إن وجدت)'),
        ),
        migrations.AddField(
            model_name='motioncontrolmodelconfig',
            name='cost_1080p',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.50'), help_text='التكلفة لكل ثانية لجودة 1080p (أو التكلفة الثابتة)', max_digits=10, verbose_name='سعر جودة 1080p (رصيد/ثانية)'),
        ),
        migrations.AddField(
            model_name='motioncontrolmodelconfig',
            name='cost_480p',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='التكلفة لكل ثانية لجودة 480p (أو التكلفة الثابتة)', max_digits=10, verbose_name='سعر جودة 480p (رصيد/ثانية)'),
        ),
        migrations.AddField(
            model_name='motioncontrolmodelconfig',
            name='cost_4k',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='التكلفة لكل ثانية لجودة 4K (أو التكلفة الثابتة)', max_digits=10, verbose_name='سعر جودة 4K (رصيد/ثانية)'),
        ),
        migrations.AddField(
            model_name='motioncontrolmodelconfig',
            name='cost_720p',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='التكلفة لكل ثانية لجودة 720p (أو التكلفة الثابتة)', max_digits=10, verbose_name='سعر جودة 720p (رصيد/ثانية)'),
        ),
        migrations.AddField(
            model_name='motioncontrolmodelconfig',
            name='max_duration',
            field=models.IntegerField(default=60, help_text='أقصى مدة فيديو مسموحة بالثواني', verbose_name='الحد الأقصى للمدة (ثواني)'),
        ),
        migrations.AddField(
            model_name='motioncontrolmodelconfig',
            name='min_duration',
            field=models.IntegerField(default=5, help_text='أقل مدة فيديو مسموحة بالثواني', verbose_name='الحد الأدنى للمدة (ثواني)'),
        ),
        migrations.AddField(
            model_name='motioncontrolmodelconfig',
            name='pricing_type',
            field=models.CharField(choices=[('per_second', 'حسب عدد الثواني (Per Second)'), ('flat', 'سعر ثابت لكل عملية (Flat Rate)')], default='per_second', help_text='طريقة احتساب التكلفة: بالثانية أو سعر ثابت', max_length=20, verbose_name='آلية التسعير'),
        ),
        migrations.AddField(
            model_name='motioncontrolmodelconfig',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='ترتيب النموذج في القوائم المنسدلة', verbose_name='ترتيب الظهور'),
        ),
        migrations.AddField(
            model_name='motioncontrolmodelconfig',
            name='supported_resolutions',
            field=models.CharField(default='480p,720p,1080p,4k', help_text='الجودات المدعومة مفصولة بفاصلة مثل: 480p,720p,1080p,4k', max_length=100, verbose_name='الجودات المدعومة'),
        ),
        migrations.AlterField(
            model_name='motioncontrolmodelconfig',
            name='allowed_wallet',
            field=models.CharField(choices=[('standard', 'الرصيد الأساسي (Standard)'), ('premium', 'الرصيد المميز (Premium)'), ('both', 'المحفظتان معاً (Both)')], default='both', help_text='نوع الرصيد المسموح بالخصم منه لهذا النموذج', max_length=20, verbose_name='المحفظة المسموحة'),
        ),
        migrations.AlterField(
            model_name='motioncontrolmodelconfig',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='التكلفة الأساسية الثابتة'),
        ),
        migrations.AlterField(
            model_name='motioncontrolmodelconfig',
            name='cost_per_second',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=10, verbose_name='التكلفة الافتراضية للثانية'),
        ),
        migrations.AlterField(
            model_name='motioncontrolmodelconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='إتاحة النموذج للمستخدمين في واجهة الاستوديو', verbose_name='مفعل في الاستوديو'),
        ),
        migrations.AlterField(
            model_name='motioncontrolmodelconfig',
            name='is_default',
            field=models.BooleanField(default=False, help_text='النموذج المختار تلقائياً عند فتح الأداة', verbose_name='نموذج افتراضي'),
        ),
        migrations.AlterField(
            model_name='motioncontrolmodelconfig',
            name='model_id',
            field=models.CharField(help_text='المعرف التقني للنموذج في Crun AI', max_length=100, unique=True, verbose_name='معرف النموذج البرمجي (Model ID)'),
        ),
        migrations.AlterField(
            model_name='motioncontrolmodelconfig',
            name='name',
            field=models.CharField(help_text='اسم النموذج الرسمي النظيف كما يظهر في واجهة الاستوديو بدون ذكر المزودات', max_length=150, verbose_name='اسم النموذج الظاهر للمستخدم'),
        ),
        migrations.AlterField(
            model_name='motioncontrolmodelconfig',
            name='provider',
            field=models.CharField(default='Crun AI', help_text='مزود الخدمة الأساسي (Crun AI)', max_length=50, verbose_name='المزود'),
        ),
        migrations.AlterField(
            model_name='motioncontrolsetting',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الأداة'),
        ),
        migrations.AlterField(
            model_name='motioncontrolsetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='وضع الصيانة'),
        ),
    ]
