from decimal import Decimal
from django.core.management.base import BaseCommand
from apps.tools.reference_to_video.models import ReferenceToVideoModelConfig, ReferenceToVideoSetting


class Command(BaseCommand):
    help = 'Seeds all 21 official Crun AI Reference-to-Video models with exact multimodal capabilities (images, video, audio), durations, and locked settings.'

    def handle(self, *args, **options):
        models_data = [
            {
                'name': 'Seedance 2.5 Cinema Pro',
                'model_id': 'seedance-2-5',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 20,
                'accepts_video_ref': True,
                'max_video_refs': 5,
                'accepts_audio_ref': True,
                'max_audio_refs': 3,
                'duration_type': 'range',
                'allowed_durations': '4-15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('4.00'),
                'cost_720p': Decimal('8.00'),
                'cost_1080p': Decimal('12.00'),
                'cost_4k': Decimal('20.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': True,
                'sort_order': 1,
            },
            {
                'name': 'Seedance 2.0 Pro',
                'model_id': 'seedance-2',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 10,
                'accepts_video_ref': True,
                'max_video_refs': 3,
                'accepts_audio_ref': True,
                'max_audio_refs': 3,
                'duration_type': 'range',
                'allowed_durations': '4-15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('4.00'),
                'cost_720p': Decimal('7.00'),
                'cost_1080p': Decimal('11.00'),
                'cost_4k': Decimal('18.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 2,
            },
            {
                'name': 'Seedance 2.0 Fast',
                'model_id': 'seedance-2-mini',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 5,
                'accepts_video_ref': True,
                'max_video_refs': 2,
                'accepts_audio_ref': True,
                'max_audio_refs': 1,
                'duration_type': 'range',
                'allowed_durations': '4-10',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.00'),
                'cost_4k': Decimal('15.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 3,
            },
            {
                'name': 'Seedance 1.5 Pro',
                'model_id': 'seedance-1-5-pro',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 3,
                'accepts_video_ref': False,
                'max_video_refs': 0,
                'accepts_audio_ref': True,
                'max_audio_refs': 1,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.00'),
                'cost_4k': Decimal('15.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 4,
            },
            {
                'name': 'MiniMax H3 Multi-Ref',
                'model_id': 'minimax-h3',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 3,
                'accepts_video_ref': True,
                'max_video_refs': 1,
                'accepts_audio_ref': False,
                'max_audio_refs': 0,
                'duration_type': 'range',
                'allowed_durations': '4-15',
                'default_duration': 6,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.50'),
                'cost_720p': Decimal('7.00'),
                'cost_1080p': Decimal('10.00'),
                'cost_4k': Decimal('16.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 5,
            },
            {
                'name': 'Agnes Video 2.5 Cinema',
                'model_id': 'agnes-video-2-5',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 4,
                'accepts_video_ref': True,
                'max_video_refs': 1,
                'accepts_audio_ref': False,
                'max_audio_refs': 0,
                'duration_type': 'range',
                'allowed_durations': '4-12',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.50'),
                'cost_720p': Decimal('7.00'),
                'cost_1080p': Decimal('10.00'),
                'cost_4k': Decimal('16.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 6,
            },
            {
                'name': 'Vidu Q3 Ultra Reference',
                'model_id': 'vidu-q3',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 5,
                'accepts_video_ref': False,
                'max_video_refs': 0,
                'accepts_audio_ref': True,
                'max_audio_refs': 1,
                'duration_type': 'discrete',
                'allowed_durations': '5,10,16',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.50'),
                'cost_720p': Decimal('7.00'),
                'cost_1080p': Decimal('11.00'),
                'cost_4k': Decimal('18.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 7,
            },
            {
                'name': 'Vidu Q2 Multi-Ref',
                'model_id': 'vidu-q2',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 3,
                'accepts_video_ref': False,
                'max_video_refs': 0,
                'accepts_audio_ref': False,
                'max_audio_refs': 0,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('5.00'),
                'cost_1080p': Decimal('8.00'),
                'cost_4k': Decimal('14.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 8,
            },
            {
                'name': 'Wan 3.0 Cinema Storyboard',
                'model_id': 'wan-3-video',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 5,
                'accepts_video_ref': False,
                'max_video_refs': 0,
                'accepts_audio_ref': True,
                'max_audio_refs': 1,
                'duration_type': 'discrete',
                'allowed_durations': '5,10,15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.50'),
                'cost_720p': Decimal('7.00'),
                'cost_1080p': Decimal('11.00'),
                'cost_4k': Decimal('18.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 9,
            },
            {
                'name': 'Wan 2.7 Multi-Reference',
                'model_id': 'wan-2-7',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 3,
                'accepts_video_ref': False,
                'max_video_refs': 0,
                'accepts_audio_ref': True,
                'max_audio_refs': 1,
                'duration_type': 'discrete',
                'allowed_durations': '5,10,15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.00'),
                'cost_4k': Decimal('15.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 10,
            },
            {
                'name': 'Wan 2.2 Animate Identity',
                'model_id': 'wan-2-2-animate',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 1,
                'accepts_video_ref': True,
                'max_video_refs': 1,
                'accepts_audio_ref': False,
                'max_audio_refs': 0,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.00'),
                'cost_4k': Decimal('15.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 11,
            },
            {
                'name': 'Kling 3.0 Cinematic Multi-Ref',
                'model_id': 'kling-3',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 4,
                'accepts_video_ref': True,
                'max_video_refs': 1,
                'accepts_audio_ref': False,
                'max_audio_refs': 0,
                'duration_type': 'discrete',
                'allowed_durations': '5,10,15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('4.00'),
                'cost_720p': Decimal('8.00'),
                'cost_1080p': Decimal('12.00'),
                'cost_4k': Decimal('20.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 12,
            },
            {
                'name': 'Kling 3.0 Motion Control',
                'model_id': 'kling-3-motion-control',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 1,
                'accepts_video_ref': True,
                'max_video_refs': 1,
                'accepts_audio_ref': False,
                'max_audio_refs': 0,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.50'),
                'cost_720p': Decimal('7.00'),
                'cost_1080p': Decimal('10.00'),
                'cost_4k': Decimal('16.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 13,
            },
            {
                'name': 'Kling 2.6 Pro Audio Reference',
                'model_id': 'kling-2-6',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 2,
                'accepts_video_ref': False,
                'max_video_refs': 0,
                'accepts_audio_ref': True,
                'max_audio_refs': 1,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.00'),
                'cost_4k': Decimal('15.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 14,
            },
            {
                'name': 'Kling 2.6 Motion Control',
                'model_id': 'kling-2-6-motion-control',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 1,
                'accepts_video_ref': True,
                'max_video_refs': 1,
                'accepts_audio_ref': False,
                'max_audio_refs': 0,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.00'),
                'cost_4k': Decimal('15.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 15,
            },
            {
                'name': 'Google Veo 3.1 Consistent Story',
                'model_id': 'veo-3-1',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 3,
                'accepts_video_ref': True,
                'max_video_refs': 1,
                'accepts_audio_ref': False,
                'max_audio_refs': 0,
                'duration_type': 'discrete',
                'allowed_durations': '4,6,8',
                'default_duration': 4,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('4.00'),
                'cost_720p': Decimal('8.00'),
                'cost_1080p': Decimal('12.00'),
                'cost_4k': Decimal('20.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 16,
            },
            {
                'name': 'PixVerse V6 Character Video',
                'model_id': 'pixverse-v6',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 2,
                'accepts_video_ref': False,
                'max_video_refs': 0,
                'accepts_audio_ref': True,
                'max_audio_refs': 1,
                'duration_type': 'discrete',
                'allowed_durations': '5,8',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.00'),
                'cost_4k': Decimal('15.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 17,
            },
            {
                'name': 'Runway Gen-4 Aleph Reference',
                'model_id': 'gen-4',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 3,
                'accepts_video_ref': True,
                'max_video_refs': 1,
                'accepts_audio_ref': False,
                'max_audio_refs': 0,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('4.00'),
                'cost_720p': Decimal('8.00'),
                'cost_1080p': Decimal('12.00'),
                'cost_4k': Decimal('20.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 18,
            },
            {
                'name': 'Hailuo 2.3 Reference',
                'model_id': 'hailuo-2-3',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 2,
                'accepts_video_ref': False,
                'max_video_refs': 0,
                'accepts_audio_ref': True,
                'max_audio_refs': 1,
                'duration_type': 'discrete',
                'allowed_durations': '6',
                'default_duration': 6,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.00'),
                'cost_4k': Decimal('15.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 19,
            },
            {
                'name': 'HappyHorse 1.1 Multi-Ref',
                'model_id': 'happyhorse-1-1',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 3,
                'accepts_video_ref': False,
                'max_video_refs': 0,
                'accepts_audio_ref': True,
                'max_audio_refs': 1,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('5.00'),
                'cost_1080p': Decimal('8.00'),
                'cost_4k': Decimal('14.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 20,
            },
            {
                'name': 'Grok Imagine Video Reference',
                'model_id': 'grok-imagine',
                'provider': 'Crun AI',
                'accepts_image_ref': True,
                'max_image_refs': 2,
                'accepts_video_ref': False,
                'max_video_refs': 0,
                'accepts_audio_ref': False,
                'max_audio_refs': 0,
                'duration_type': 'discrete',
                'allowed_durations': '5',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('5.00'),
                'cost_1080p': Decimal('8.00'),
                'cost_4k': Decimal('14.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 21,
            },
        ]

        count = 0
        for m in models_data:
            existing = ReferenceToVideoModelConfig.objects.filter(model_id=m['model_id']).first()
            if existing:
                ReferenceToVideoModelConfig.objects.filter(pk=existing.pk).update(**m)
            else:
                ReferenceToVideoModelConfig.objects.create(**m)
            count += 1

        setting, _ = ReferenceToVideoSetting.objects.get_or_create(id=1)
        setting.is_enabled = True
        setting.maintenance_mode = False
        setting.max_reference_images = 20
        setting.max_file_size_mb = 50
        setting.save()

        self.stdout.write(self.style.SUCCESS(f"Successfully seeded {count} official Crun AI Reference-to-Video models with exact multimodal capabilities and locked settings!"))
