from decimal import Decimal
from django.core.management.base import BaseCommand
from apps.tools.avatar_video.models import AvatarVideoModelConfig


class Command(BaseCommand):
    help = 'Seeds all 28 official Crun AI Avatar & Digital Human models with exact resolutions, durations, and pricing'

    def handle(self, *args, **options):
        models_data = [
            {
                'name': 'AI Avatar Studio Pro (Universal Digital Human)',
                'model_id': 'crun-avatar-pro',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 120,
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.50'),
                'cost_4k': Decimal('6.00'),
                'cost_per_second': Decimal('2.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': True,
                'sort_order': 1,
            },
            {
                'name': 'Hedra Character 2.0 Ultra (Realistic Presenter)',
                'model_id': 'hedra-character-2-ultra',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('2.50'),
                'cost_1080p': Decimal('4.00'),
                'cost_4k': Decimal('7.00'),
                'cost_per_second': Decimal('2.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 2,
            },
            {
                'name': 'Hedra Character 1.0 HD (Fast Speech)',
                'model_id': 'hedra-character-1-hd',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('1.80'),
                'cost_1080p': Decimal('3.00'),
                'cost_4k': Decimal('5.50'),
                'cost_per_second': Decimal('1.80'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 3,
            },
            {
                'name': 'LivePortrait Pro Talking Head (Expressive Portrait)',
                'model_id': 'liveportrait-pro-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('0.80'),
                'cost_720p': Decimal('1.50'),
                'cost_1080p': Decimal('2.80'),
                'cost_4k': Decimal('5.00'),
                'cost_per_second': Decimal('1.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 4,
            },
            {
                'name': 'LivePortrait 2.0 Realtime Facial Animator',
                'model_id': 'liveportrait-2-realtime',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('0.90'),
                'cost_720p': Decimal('1.60'),
                'cost_1080p': Decimal('3.00'),
                'cost_4k': Decimal('5.20'),
                'cost_per_second': Decimal('1.60'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 5,
            },
            {
                'name': 'DreamActor 2.0 Full Body Avatar (ByteDance)',
                'model_id': 'dreamactor-2-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.80'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('5.00'),
                'cost_4k': Decimal('8.50'),
                'cost_per_second': Decimal('3.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 6,
            },
            {
                'name': 'DreamActor 1.5 Motion Transfer Human',
                'model_id': 'dreamactor-1.5-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('2.50'),
                'cost_1080p': Decimal('4.20'),
                'cost_4k': Decimal('7.50'),
                'cost_per_second': Decimal('2.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 7,
            },
            {
                'name': 'Kling 4.0 Digital Presenter Ultra',
                'model_id': 'kling-4-avatar-ultra',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('4.50'),
                'cost_1080p': Decimal('7.00'),
                'cost_4k': Decimal('12.00'),
                'cost_per_second': Decimal('4.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 8,
            },
            {
                'name': 'Kling 3.0 Avatar Presenter (Cinematic)',
                'model_id': 'kling-3-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('3.50'),
                'cost_1080p': Decimal('5.50'),
                'cost_4k': Decimal('9.50'),
                'cost_per_second': Decimal('3.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 9,
            },
            {
                'name': 'Kling 2.6 Native Avatar & Voice',
                'model_id': 'kling-2.6-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.80'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('4.80'),
                'cost_4k': Decimal('8.50'),
                'cost_per_second': Decimal('3.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 10,
            },
            {
                'name': 'Wan 3.0 Audio-Visual Digital Human',
                'model_id': 'wan-3-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.20'),
                'cost_720p': Decimal('3.80'),
                'cost_1080p': Decimal('6.00'),
                'cost_4k': Decimal('10.50'),
                'cost_per_second': Decimal('3.80'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 11,
            },
            {
                'name': 'Wan 2.7 Ultra Presenter (Multilingual)',
                'model_id': 'wan-2.7-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.60'),
                'cost_720p': Decimal('2.80'),
                'cost_1080p': Decimal('4.50'),
                'cost_4k': Decimal('8.00'),
                'cost_per_second': Decimal('2.80'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 12,
            },
            {
                'name': 'Wan 2.5 Preview Speech Avatar',
                'model_id': 'wan-2.5-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.40'),
                'cost_720p': Decimal('2.40'),
                'cost_1080p': Decimal('4.00'),
                'cost_4k': Decimal('7.20'),
                'cost_per_second': Decimal('2.40'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 13,
            },
            {
                'name': 'Wan 2.2 Animate Digital Character',
                'model_id': 'wan-2.2-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.20'),
                'cost_720p': Decimal('2.20'),
                'cost_1080p': Decimal('3.80'),
                'cost_4k': Decimal('6.80'),
                'cost_per_second': Decimal('2.20'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 14,
            },
            {
                'name': 'Google Veo 3.1 Digital Actor Studio',
                'model_id': 'veo-3.1-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('5.00'),
                'cost_1080p': Decimal('8.00'),
                'cost_4k': Decimal('14.00'),
                'cost_per_second': Decimal('5.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 15,
            },
            {
                'name': 'Google Veo 2 Human Presenter',
                'model_id': 'veo-2-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.20'),
                'cost_720p': Decimal('3.80'),
                'cost_1080p': Decimal('6.00'),
                'cost_4k': Decimal('10.00'),
                'cost_per_second': Decimal('3.80'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 16,
            },
            {
                'name': 'Sora 2 Photorealistic Human Actor',
                'model_id': 'sora-2-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('3.50'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.50'),
                'cost_4k': Decimal('16.00'),
                'cost_per_second': Decimal('6.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 17,
            },
            {
                'name': 'Seedance 2.5 Dialogue & Presenter Video',
                'model_id': 'seedance-2.5-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.80'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('5.00'),
                'cost_4k': Decimal('8.50'),
                'cost_per_second': Decimal('3.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 18,
            },
            {
                'name': 'MiniMax H3 Speech-to-Avatar Motion',
                'model_id': 'minimax-h3-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.60'),
                'cost_720p': Decimal('2.80'),
                'cost_1080p': Decimal('4.60'),
                'cost_4k': Decimal('8.00'),
                'cost_per_second': Decimal('2.80'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 19,
            },
            {
                'name': 'Vidu Q3 Ultra Talking Presenter',
                'model_id': 'vidu-q3-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.80'),
                'cost_720p': Decimal('3.20'),
                'cost_1080p': Decimal('5.20'),
                'cost_4k': Decimal('9.00'),
                'cost_per_second': Decimal('3.20'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 20,
            },
            {
                'name': 'Hailuo 2.3 Audio-Visual Human Studio',
                'model_id': 'hailuo-2.3-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('3.40'),
                'cost_1080p': Decimal('5.50'),
                'cost_4k': Decimal('9.50'),
                'cost_per_second': Decimal('3.40'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 21,
            },
            {
                'name': 'Runway Gen-4 Aleph Digital Character',
                'model_id': 'runway-gen4-avatar',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('5.50'),
                'cost_1080p': Decimal('8.50'),
                'cost_4k': Decimal('15.00'),
                'cost_per_second': Decimal('5.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 22,
            },
            {
                'name': 'AI News Anchor 4K Broadcast Studio',
                'model_id': 'crun-avatar-news-4k',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 120,
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('2.50'),
                'cost_1080p': Decimal('4.20'),
                'cost_4k': Decimal('7.50'),
                'cost_per_second': Decimal('2.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 23,
            },
            {
                'name': 'AI Corporate Executive Presenter',
                'model_id': 'crun-avatar-corporate',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 120,
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('2.50'),
                'cost_1080p': Decimal('4.20'),
                'cost_4k': Decimal('7.50'),
                'cost_per_second': Decimal('2.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 24,
            },
            {
                'name': 'AI Social Media Influencer & Vlogger',
                'model_id': 'crun-avatar-influencer',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.50'),
                'cost_4k': Decimal('6.00'),
                'cost_per_second': Decimal('2.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 25,
            },
            {
                'name': 'AI E-Commerce & Product Showcaser',
                'model_id': 'crun-avatar-ecommerce',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.20'),
                'cost_720p': Decimal('2.20'),
                'cost_1080p': Decimal('3.80'),
                'cost_4k': Decimal('6.80'),
                'cost_per_second': Decimal('2.20'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 26,
            },
            {
                'name': 'AI Academic Educator & Lecturer',
                'model_id': 'crun-avatar-educator',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 120,
                'cost_480p': Decimal('1.20'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.50'),
                'cost_4k': Decimal('6.50'),
                'cost_per_second': Decimal('2.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 27,
            },
            {
                'name': 'AI Anime & Stylized 3D Persona',
                'model_id': 'crun-avatar-stylized',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.00'),
                'cost_720p': Decimal('1.80'),
                'cost_1080p': Decimal('3.00'),
                'cost_4k': Decimal('5.50'),
                'cost_per_second': Decimal('1.80'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 28,
            },
        ]

        count = 0
        for m_data in models_data:
            existing = AvatarVideoModelConfig.objects.filter(model_id=m_data['model_id']).first()
            if existing:
                AvatarVideoModelConfig.objects.filter(id=existing.id).update(**m_data)
            else:
                AvatarVideoModelConfig.objects.create(**m_data)
            count += 1

        self.stdout.write(self.style.SUCCESS(f"Successfully seeded {count} official Crun AI Avatar & Digital Human models!"))
