# Generated by Django 5.1.15 on 2026-10-01 04:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('tts', 'Text to Voice'), ('stt', 'Voice to Text'), ('text_to_video', 'Text to Video'), ('image_to_video', 'Image to Video'), ('reference_to_video', 'Reference to Video'), ('lipsync', 'Lip Sync'), ('motion_control', 'Motion Control'), ('text_to_image', 'Text to Image'), ('avatar_video', 'Avatar to Video')], db_index=True, max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('result_url', models.URLField(blank=True, help_text='MinIO S3 Presigned URL', max_length=1000, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('input_file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('standard_credits_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('premium_credits_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('meta_info', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='Async Queue Task ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generation History',
                'verbose_name_plural': 'Generation Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
