# Generated by Django 5.1.15 on 2026-10-01 15:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_to_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagetovideomodelconfig',
            options={'ordering': ['sort_order', '-is_default', 'name'], 'verbose_name': 'نموذج تحريك الصور (I2V Model)', 'verbose_name_plural': 'نماذج تحريك الصور (I2V Models)'},
        ),
        migrations.AlterModelOptions(
            name='imagetovideosetting',
            options={'verbose_name': 'إعدادات عامة لتحريك الصور إلى فيديو', 'verbose_name_plural': 'إعدادات عامة لتحريك الصور إلى فيديو'},
        ),
        migrations.RemoveField(
            model_name='imagetovideomodelconfig',
            name='cost_fixed',
        ),
        migrations.RemoveField(
            model_name='imagetovideomodelconfig',
            name='cost_per_second',
        ),
        migrations.AddField(
            model_name='imagetovideomodelconfig',
            name='accepts_end_frame',
            field=models.BooleanField(default=False, help_text='إذا كان مفعلاً، يمكن للمستخدم رفع صورة بداية وصورة نهاية اختيارية للتحول والانتقال بينهما.', verbose_name='دعم صورة النهاية (End Frame)'),
        ),
        migrations.AddField(
            model_name='imagetovideomodelconfig',
            name='allowed_durations',
            field=models.CharField(default='5,10', help_text='المدد المسموحة مفصولة بفاصلة (مثال: 5,10) أو نطاق مرن (مثال: 4-15)', max_length=100, verbose_name='المدد الزمنية المتاحة (ثوانٍ)'),
        ),
        migrations.AddField(
            model_name='imagetovideomodelconfig',
            name='cost_1080p',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='الكريديت المطلوب لكل ثانية أو للعملية الواحدة لدقة 1080p', max_digits=10, verbose_name='سعر 1080p'),
        ),
        migrations.AddField(
            model_name='imagetovideomodelconfig',
            name='cost_480p',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='الكريديت المطلوب لكل ثانية أو للعملية الواحدة لدقة 480p', max_digits=10, verbose_name='سعر 480p'),
        ),
        migrations.AddField(
            model_name='imagetovideomodelconfig',
            name='cost_4k',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='الكريديت المطلوب لكل ثانية أو للعملية الواحدة لدقة 4K', max_digits=10, verbose_name='سعر 4K'),
        ),
        migrations.AddField(
            model_name='imagetovideomodelconfig',
            name='cost_720p',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='الكريديت المطلوب لكل ثانية أو للعملية الواحدة لدقة 720p', max_digits=10, verbose_name='سعر 720p'),
        ),
        migrations.AddField(
            model_name='imagetovideomodelconfig',
            name='default_duration',
            field=models.IntegerField(default=5, verbose_name='المدة الافتراضية (ثوانٍ)'),
        ),
        migrations.AddField(
            model_name='imagetovideomodelconfig',
            name='duration_type',
            field=models.CharField(choices=[('discrete', 'مدد محددة (Discrete)'), ('range', 'نطاق مرن (Range)')], default='discrete', max_length=20, verbose_name='نوع المدة الزمنية'),
        ),
        migrations.AddField(
            model_name='imagetovideomodelconfig',
            name='pricing_type',
            field=models.CharField(choices=[('per_second', 'بالثانية (Per Second)'), ('per_request', 'بالعملية/الريكوست (Per Request)')], default='per_second', max_length=20, verbose_name='طريقة التسعير'),
        ),
        migrations.AddField(
            model_name='imagetovideomodelconfig',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AddField(
            model_name='imagetovideomodelconfig',
            name='supported_resolutions',
            field=models.CharField(default='720p,1080p', help_text='الجودات المدعومة مفصولة بفاصلة مثل: 480p,720p,1080p,4k', max_length=100, verbose_name='الجودات المدعومة'),
        ),
        migrations.AlterField(
            model_name='imagetovideomodelconfig',
            name='allowed_wallet',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة المسموحة'),
        ),
        migrations.AlterField(
            model_name='imagetovideomodelconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل للاستخدام'),
        ),
        migrations.AlterField(
            model_name='imagetovideomodelconfig',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='النموذج الافتراضي'),
        ),
        migrations.AlterField(
            model_name='imagetovideomodelconfig',
            name='model_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='معرف النموذج (Model ID)'),
        ),
        migrations.AlterField(
            model_name='imagetovideomodelconfig',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم النموذج'),
        ),
        migrations.AlterField(
            model_name='imagetovideomodelconfig',
            name='provider',
            field=models.CharField(default='Crun AI', max_length=50, verbose_name='المزود'),
        ),
        migrations.AlterField(
            model_name='imagetovideosetting',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الأداة عموماً'),
        ),
        migrations.AlterField(
            model_name='imagetovideosetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='وضع الصيانة'),
        ),
        migrations.AlterField(
            model_name='imagetovideosetting',
            name='max_image_size_mb',
            field=models.IntegerField(default=20, verbose_name='الحد الأقصى لحجم الصورة (ميغابايت)'),
        ),
    ]
