# Generated by Django 5.1.15 on 2026-10-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_to_video', '0002_alter_imagetovideomodelconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetovideomodelconfig',
            name='image_input_type',
            field=models.CharField(choices=[('single', 'صورة واحدة (Start Frame)'), ('start_end', 'صورتان (Start + End Frame)'), ('multi_5', 'حتى 5 صور (Multi-Reference / Storyboard)')], default='single', max_length=20, verbose_name='نمط إدخال الصور'),
        ),
        migrations.AddField(
            model_name='imagetovideomodelconfig',
            name='max_input_images',
            field=models.IntegerField(default=1, verbose_name='الحد الأقصى للصور المقبولة (1 أو 2 أو 5)'),
        ),
    ]
