from decimal import Decimal
from django.core.management.base import BaseCommand
from apps.tools.motion_control.models import MotionControlModelConfig


class Command(BaseCommand):
    help = 'Seeds all 25 official Crun AI Motion Control models with exact resolutions, durations, and pricing'

    def handle(self, *args, **options):
        models_data = [
            {
                'name': 'AI Mimic Motion Pro (Universal Body & Pose)',
                'model_id': 'crun-mimic-motion-pro',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.20'),
                'cost_720p': Decimal('2.00'),
                'cost_1080p': Decimal('3.50'),
                'cost_4k': Decimal('6.00'),
                'cost_per_second': Decimal('2.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': True,
                'sort_order': 1,
            },
            {
                'name': 'Kling 4.0 Cinematic Motion Control',
                'model_id': 'kling-4-motion-control',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('4.50'),
                'cost_1080p': Decimal('7.00'),
                'cost_4k': Decimal('12.00'),
                'cost_per_second': Decimal('4.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 2,
            },
            {
                'name': 'Kling 3.0 Motion Control & Dance',
                'model_id': 'kling-3-motion-control',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('3.50'),
                'cost_1080p': Decimal('5.50'),
                'cost_4k': Decimal('9.50'),
                'cost_per_second': Decimal('3.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 3,
            },
            {
                'name': 'Kling 2.6 Motion Transfer & Pose',
                'model_id': 'kling-2.6-motion-control',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.80'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('4.80'),
                'cost_4k': Decimal('8.50'),
                'cost_per_second': Decimal('3.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 4,
            },
            {
                'name': 'Kling 2.5 Turbo Fast Motion',
                'model_id': 'kling-2.5-turbo-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.20'),
                'cost_720p': Decimal('2.20'),
                'cost_1080p': Decimal('3.60'),
                'cost_4k': Decimal('6.50'),
                'cost_per_second': Decimal('2.20'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 5,
            },
            {
                'name': 'Hailuo 2.3 Complex Motion & Dance Studio',
                'model_id': 'hailuo-2.3-dance-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('3.40'),
                'cost_1080p': Decimal('5.50'),
                'cost_4k': Decimal('9.50'),
                'cost_per_second': Decimal('3.40'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 6,
            },
            {
                'name': 'Wan 3.0 Dynamic Motion & Transfer',
                'model_id': 'wan-3-motion-control',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.20'),
                'cost_720p': Decimal('3.80'),
                'cost_1080p': Decimal('6.00'),
                'cost_4k': Decimal('10.50'),
                'cost_per_second': Decimal('3.80'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 7,
            },
            {
                'name': 'Wan 2.5 Motion & Camera Direction',
                'model_id': 'wan-2.5-motion-control',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.40'),
                'cost_720p': Decimal('2.40'),
                'cost_1080p': Decimal('4.00'),
                'cost_4k': Decimal('7.20'),
                'cost_per_second': Decimal('2.40'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 8,
            },
            {
                'name': 'Wan 2.2 Animate Character & Video Pose',
                'model_id': 'wan-2.2-animate-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.20'),
                'cost_720p': Decimal('2.20'),
                'cost_1080p': Decimal('3.80'),
                'cost_4k': Decimal('6.80'),
                'cost_per_second': Decimal('2.20'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 9,
            },
            {
                'name': 'Bytedance DreamActor 2.0 Motion Transfer',
                'model_id': 'dreamactor-2-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.80'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('5.00'),
                'cost_4k': Decimal('8.50'),
                'cost_per_second': Decimal('3.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 10,
            },
            {
                'name': 'Bytedance DreamActor 1.5 Pose Replicator',
                'model_id': 'dreamactor-1.5-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('2.50'),
                'cost_1080p': Decimal('4.20'),
                'cost_4k': Decimal('7.50'),
                'cost_per_second': Decimal('2.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 11,
            },
            {
                'name': 'Seedance 2.5 Director-Level Motion & Camera',
                'model_id': 'seedance-2.5-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.80'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('5.00'),
                'cost_4k': Decimal('8.50'),
                'cost_per_second': Decimal('3.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 12,
            },
            {
                'name': 'Seedance 2.0 Dance & Action Choreographer',
                'model_id': 'seedance-2.0-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.60'),
                'cost_720p': Decimal('2.80'),
                'cost_1080p': Decimal('4.60'),
                'cost_4k': Decimal('8.00'),
                'cost_per_second': Decimal('2.80'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 13,
            },
            {
                'name': 'HappyHorse 1.1 Cinematic Motion Control',
                'model_id': 'happyhorse-1.1-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('2.60'),
                'cost_1080p': Decimal('4.40'),
                'cost_4k': Decimal('7.80'),
                'cost_per_second': Decimal('2.60'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 14,
            },
            {
                'name': 'HappyHorse 1.0 Audio-Synced Motion',
                'model_id': 'happyhorse-1.0-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '480p,720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.20'),
                'cost_720p': Decimal('2.20'),
                'cost_1080p': Decimal('3.80'),
                'cost_4k': Decimal('6.80'),
                'cost_per_second': Decimal('2.20'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 15,
            },
            {
                'name': 'Runway Gen-4 Camera & Dynamic Motion',
                'model_id': 'runway-gen4-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('5.50'),
                'cost_1080p': Decimal('8.50'),
                'cost_4k': Decimal('15.00'),
                'cost_per_second': Decimal('5.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 16,
            },
            {
                'name': 'Google Veo 3.1 Advanced Motion Director',
                'model_id': 'veo-3.1-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('5.00'),
                'cost_1080p': Decimal('8.00'),
                'cost_4k': Decimal('14.00'),
                'cost_per_second': Decimal('5.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 17,
            },
            {
                'name': 'Google Veo 2 Motion Transfer',
                'model_id': 'veo-2-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.20'),
                'cost_720p': Decimal('3.80'),
                'cost_1080p': Decimal('6.00'),
                'cost_4k': Decimal('10.00'),
                'cost_per_second': Decimal('3.80'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 18,
            },
            {
                'name': 'Sora 2 Dynamic Human & Camera Motion',
                'model_id': 'sora-2-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('3.50'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.50'),
                'cost_4k': Decimal('16.00'),
                'cost_per_second': Decimal('6.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 19,
            },
            {
                'name': 'MiniMax H3 Character Consistency Motion',
                'model_id': 'minimax-h3-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.60'),
                'cost_720p': Decimal('2.80'),
                'cost_1080p': Decimal('4.60'),
                'cost_4k': Decimal('8.00'),
                'cost_per_second': Decimal('2.80'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 20,
            },
            {
                'name': 'Vidu Q3 Ultra Motion & Flow Control',
                'model_id': 'vidu-q3-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('1.80'),
                'cost_720p': Decimal('3.20'),
                'cost_1080p': Decimal('5.20'),
                'cost_4k': Decimal('9.00'),
                'cost_per_second': Decimal('3.20'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 21,
            },
            {
                'name': 'AI Martial Arts & Action Replicator',
                'model_id': 'crun-action-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('3.50'),
                'cost_1080p': Decimal('5.80'),
                'cost_4k': Decimal('10.00'),
                'cost_per_second': Decimal('3.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 22,
            },
            {
                'name': 'AI Street & Pop Dance Choreographer',
                'model_id': 'crun-dance-choreographer',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('3.50'),
                'cost_1080p': Decimal('5.80'),
                'cost_4k': Decimal('10.00'),
                'cost_per_second': Decimal('3.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 23,
            },
            {
                'name': 'AI Sports & Athletic Motion Replicator',
                'model_id': 'crun-sports-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('3.50'),
                'cost_1080p': Decimal('5.80'),
                'cost_4k': Decimal('10.00'),
                'cost_per_second': Decimal('3.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 24,
            },
            {
                'name': 'AI Fashion Model Walk & Runway Pose',
                'model_id': 'crun-fashion-runway-motion',
                'provider': 'Crun AI',
                'pricing_type': 'per_second',
                'supported_resolutions': '720p,1080p,4k',
                'min_duration': 5,
                'max_duration': 60,
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('3.50'),
                'cost_1080p': Decimal('5.80'),
                'cost_4k': Decimal('10.00'),
                'cost_per_second': Decimal('3.50'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 25,
            },
        ]

        count = 0
        for m_data in models_data:
            existing = MotionControlModelConfig.objects.filter(model_id=m_data['model_id']).first()
            if existing:
                MotionControlModelConfig.objects.filter(id=existing.id).update(**m_data)
            else:
                MotionControlModelConfig.objects.create(**m_data)
            count += 1

        self.stdout.write(self.style.SUCCESS(f"Successfully seeded {count} official Crun AI Motion Control models!"))
