from decimal import Decimal
from django.core.management.base import BaseCommand
from apps.tools.image_to_video.models import ImageToVideoModelConfig


class Command(BaseCommand):
    help = 'Seeds all 27 official Crun AI Image-to-Video (I2V) models with verified durations, image count, and resolutions.'

    def handle(self, *args, **options):
        models_data = [
            {
                'name': 'Kling 3.0 Cinematic Pro',
                'model_id': 'kling/v3.0-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': True,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.00'),
                'cost_4k': Decimal('16.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': True,
                'sort_order': 1,
            },
            {
                'name': 'Kling 2.6 Pro Audio',
                'model_id': 'kling/v2.6-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': True,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('5.50'),
                'cost_1080p': Decimal('8.50'),
                'cost_4k': Decimal('15.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 2,
            },
            {
                'name': 'Google Veo 3.1 Studio',
                'model_id': 'google/veo3-1-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '4,6,8',
                'default_duration': 6,
                'supported_resolutions': '720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('4.00'),
                'cost_720p': Decimal('8.00'),
                'cost_1080p': Decimal('12.00'),
                'cost_4k': Decimal('22.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 3,
            },
            {
                'name': 'Google Veo 2 Ultra',
                'model_id': 'google/veo-2-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '5,6,8',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.50'),
                'cost_720p': Decimal('7.00'),
                'cost_1080p': Decimal('10.00'),
                'cost_4k': Decimal('18.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 4,
            },
            {
                'name': 'Wan 3.0 Video',
                'model_id': 'alibaba/wan-3.0-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': True,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.50'),
                'cost_1080p': Decimal('7.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 5,
            },
            {
                'name': 'Wan 2.7 Video',
                'model_id': 'alibaba/wan-2.7-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': True,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.80'),
                'cost_720p': Decimal('4.00'),
                'cost_1080p': Decimal('6.50'),
                'cost_4k': Decimal('11.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 6,
            },
            {
                'name': 'Wan 2.5 Preview',
                'model_id': 'alibaba/wan-2.5-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('3.50'),
                'cost_1080p': Decimal('5.50'),
                'cost_4k': Decimal('10.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 7,
            },
            {
                'name': 'ByteDance Seedance 2.5',
                'model_id': 'bytedance/seedance-2.5-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': True,
                'duration_type': 'range',
                'allowed_durations': '4-15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('5.00'),
                'cost_1080p': Decimal('8.00'),
                'cost_4k': Decimal('15.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 8,
            },
            {
                'name': 'ByteDance Seedance 2.0',
                'model_id': 'bytedance/seedance-2.0-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': True,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.50'),
                'cost_1080p': Decimal('7.00'),
                'cost_4k': Decimal('13.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 9,
            },
            {
                'name': 'Runway Gen-4 Aleph',
                'model_id': 'runway/gen-4-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('4.00'),
                'cost_720p': Decimal('7.50'),
                'cost_1080p': Decimal('11.00'),
                'cost_4k': Decimal('18.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 10,
            },
            {
                'name': 'Runway Gen-3 Alpha',
                'model_id': 'runway/gen-3-alpha-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.50'),
                'cost_720p': Decimal('6.50'),
                'cost_1080p': Decimal('9.50'),
                'cost_4k': Decimal('16.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 11,
            },
            {
                'name': 'Kling 1.6 Standard',
                'model_id': 'kling/v1.6-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': True,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.50'),
                'cost_1080p': Decimal('7.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 12,
            },
            {
                'name': 'MiniMax H3',
                'model_id': 'minimax/h3-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '6,10',
                'default_duration': 6,
                'supported_resolutions': '720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.00'),
                'cost_4k': Decimal('16.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 13,
            },
            {
                'name': 'Hailuo 2.3 Artistic Motion',
                'model_id': 'hailuo/v2.3-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '6,10',
                'default_duration': 6,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.00'),
                'cost_4k': Decimal('15.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 14,
            },
            {
                'name': 'Vidu Q3 Ultra',
                'model_id': 'vidu/q3-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': True,
                'duration_type': 'discrete',
                'allowed_durations': '4,8',
                'default_duration': 4,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.50'),
                'cost_1080p': Decimal('7.50'),
                'cost_4k': Decimal('13.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 15,
            },
            {
                'name': 'Vidu Q2',
                'model_id': 'vidu/q2-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '4,8',
                'default_duration': 4,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.80'),
                'cost_720p': Decimal('4.00'),
                'cost_1080p': Decimal('6.50'),
                'cost_4k': Decimal('11.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 16,
            },
            {
                'name': 'PixVerse V6',
                'model_id': 'pixverse/v6-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': True,
                'duration_type': 'discrete',
                'allowed_durations': '5,8',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.50'),
                'cost_1080p': Decimal('7.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 17,
            },
            {
                'name': 'Alibaba HappyHorse 1.1',
                'model_id': 'alibaba/happyhorse-1.1-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'range',
                'allowed_durations': '3-10',
                'default_duration': 5,
                'supported_resolutions': '1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('5.00'),
                'cost_1080p': Decimal('7.50'),
                'cost_4k': Decimal('14.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 18,
            },
            {
                'name': 'Agnes Video 2.5 Cinema',
                'model_id': 'agnes/v2.5-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': True,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.50'),
                'cost_720p': Decimal('7.00'),
                'cost_1080p': Decimal('10.50'),
                'cost_4k': Decimal('18.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 19,
            },
            {
                'name': 'Agnes Video 2.0 Studio',
                'model_id': 'agnes/v2.0-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('5.50'),
                'cost_1080p': Decimal('8.50'),
                'cost_4k': Decimal('15.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 20,
            },
            {
                'name': 'OpenAI Sora 2 Motion',
                'model_id': 'openai/sora-2-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '5,10,15,20',
                'default_duration': 5,
                'supported_resolutions': '1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('5.00'),
                'cost_720p': Decimal('9.00'),
                'cost_1080p': Decimal('14.00'),
                'cost_4k': Decimal('25.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 21,
            },
            {
                'name': 'xAI Grok Imagine Video 1.5',
                'model_id': 'grok-imagine/i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'range',
                'allowed_durations': '1-15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.50'),
                'cost_1080p': Decimal('7.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 22,
            },
            {
                'name': 'Luma Ray 2 Studio',
                'model_id': 'luma/ray-2-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': True,
                'duration_type': 'discrete',
                'allowed_durations': '5,9',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.50'),
                'cost_720p': Decimal('6.50'),
                'cost_1080p': Decimal('9.50'),
                'cost_4k': Decimal('16.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 23,
            },
            {
                'name': 'Pika 2.1 Motion',
                'model_id': 'pika/v2.1-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '4,8',
                'default_duration': 4,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('5.00'),
                'cost_1080p': Decimal('8.00'),
                'cost_4k': Decimal('14.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 24,
            },
            {
                'name': 'Tencent Hunyuan Video',
                'model_id': 'tencent/hunyuan-video-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '5,9',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('5.00'),
                'cost_1080p': Decimal('8.00'),
                'cost_4k': Decimal('14.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 25,
            },
            {
                'name': 'CogVideoX 5B High-Speed',
                'model_id': 'thudm/cogvideox-5b-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '6',
                'default_duration': 6,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.00'),
                'cost_1080p': Decimal('6.50'),
                'cost_4k': Decimal('11.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 26,
            },
            {
                'name': 'Lightricks LTX Video Turbo',
                'model_id': 'lightricks/ltx-video-i2v',
                'provider': 'Crun AI',
                'accepts_end_frame': False,
                'duration_type': 'discrete',
                'allowed_durations': '5',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.00'),
                'cost_1080p': Decimal('6.50'),
                'cost_4k': Decimal('11.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 27,
            },
        ]

        count = 0
        for m in models_data:
            obj, created = ImageToVideoModelConfig.objects.update_or_create(
                model_id=m['model_id'],
                defaults=m
            )
            count += 1
            status = "Created" if created else "Updated"
            self.stdout.write(self.style.SUCCESS(f"[{count}/27] {status}: {obj.name} (Images: {'2 (Start+End)' if obj.accepts_end_frame else '1 (Start)'})"))

        self.stdout.write(self.style.SUCCESS(f"\nSuccessfully seeded all {count} Image-to-Video models!"))
