from decimal import Decimal
from django.core.management.base import BaseCommand
from apps.tools.text_to_video.models import TextToVideoModelConfig, TextToVideoSetting


class Command(BaseCommand):
    help = 'Seeds all 19 official Crun AI Text-to-Video models with exact resolutions, durations, and pricing'

    def handle(self, *args, **options):
        # 1. Ensure Setting exists
        TextToVideoSetting.objects.get_or_create(
            id=1,
            defaults={'is_enabled': True, 'maintenance_mode': False, 'max_prompt_length': 1000}
        )

        models_data = [
            {
                'name': 'Kling 3.0 Cinematic Pro',
                'model_id': 'kling/v3.0-t2v',
                'provider': 'Crun AI',
                'duration_type': 'discrete',
                'allowed_durations': '5,10,15,30',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('9.00'),
                'cost_4k': Decimal('16.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': True,
                'sort_order': 0,
            },
            {
                'name': 'Google Veo 3.1 Studio',
                'model_id': 'google/veo3-1-t2v',
                'provider': 'Crun AI',
                'duration_type': 'discrete',
                'allowed_durations': '4,6,8',
                'default_duration': 6,
                'supported_resolutions': '720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('4.00'),
                'cost_720p': Decimal('8.00'),
                'cost_1080p': Decimal('12.00'),
                'cost_4k': Decimal('20.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 1,
            },
            {
                'name': 'Google Veo 2 Ultra',
                'model_id': 'google/veo-2-t2v',
                'provider': 'Crun AI',
                'duration_type': 'discrete',
                'allowed_durations': '5,6,8',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.50'),
                'cost_720p': Decimal('7.00'),
                'cost_1080p': Decimal('10.00'),
                'cost_4k': Decimal('18.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 2,
            },
            {
                'name': 'Wan 3.0 Video',
                'model_id': 'alibaba/wan-3.0-t2v',
                'provider': 'Crun AI',
                'duration_type': 'range',
                'allowed_durations': '2-30',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.00'),
                'cost_1080p': Decimal('7.00'),
                'cost_4k': Decimal('14.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 3,
            },
            {
                'name': 'Wan 2.7 Video',
                'model_id': 'alibaba/wan-2.7-t2v',
                'provider': 'Crun AI',
                'duration_type': 'range',
                'allowed_durations': '2-15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.80'),
                'cost_720p': Decimal('3.50'),
                'cost_1080p': Decimal('6.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 4,
            },
            {
                'name': 'Wan 2.5 Preview',
                'model_id': 'alibaba/wan-2.5-t2v',
                'provider': 'Crun AI',
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('5.00'),
                'cost_4k': Decimal('10.00'),
                'allowed_wallet': 'standard',
                'is_active': True,
                'is_default': False,
                'sort_order': 5,
            },
            {
                'name': 'ByteDance Seedance 2.5',
                'model_id': 'bytedance/seedance-2.5-t2v',
                'provider': 'Crun AI',
                'duration_type': 'range',
                'allowed_durations': '4-30',
                'default_duration': 6,
                'supported_resolutions': '480p,720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('5.00'),
                'cost_1080p': Decimal('8.00'),
                'cost_4k': Decimal('16.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 6,
            },
            {
                'name': 'ByteDance Seedance 2.0',
                'model_id': 'bytedance/seedance-2.0-t2v',
                'provider': 'Crun AI',
                'duration_type': 'range',
                'allowed_durations': '4-15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.00'),
                'cost_1080p': Decimal('7.00'),
                'cost_4k': Decimal('14.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 7,
            },
            {
                'name': 'OpenAI Sora 2',
                'model_id': 'openai/sora-2-t2v',
                'provider': 'Crun AI',
                'duration_type': 'discrete',
                'allowed_durations': '5,10,15,20,25',
                'default_duration': 5,
                'supported_resolutions': '1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('6.00'),
                'cost_720p': Decimal('8.00'),
                'cost_1080p': Decimal('12.00'),
                'cost_4k': Decimal('24.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 8,
            },
            {
                'name': 'Runway Gen-4 Aleph',
                'model_id': 'runway/gen-4-t2v',
                'provider': 'Crun AI',
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.50'),
                'cost_720p': Decimal('6.00'),
                'cost_1080p': Decimal('10.00'),
                'cost_4k': Decimal('18.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 9,
            },
            {
                'name': 'Runway Gen-3 Alpha',
                'model_id': 'runway/gen-3-alpha-t2v',
                'provider': 'Crun AI',
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('3.00'),
                'cost_720p': Decimal('5.00'),
                'cost_1080p': Decimal('8.00'),
                'cost_4k': Decimal('15.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 10,
            },
            {
                'name': 'Kling 1.6 Standard',
                'model_id': 'kling/v1.6-t2v',
                'provider': 'Crun AI',
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('4.00'),
                'cost_1080p': Decimal('6.50'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'standard',
                'is_active': True,
                'is_default': False,
                'sort_order': 11,
            },
            {
                'name': 'xAI Grok Imagine Video 1.5',
                'model_id': 'grok-imagine/t2v',
                'provider': 'Crun AI',
                'duration_type': 'range',
                'allowed_durations': '1-15',
                'default_duration': 6,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('3.50'),
                'cost_1080p': Decimal('6.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 12,
            },
            {
                'name': 'MiniMax H3',
                'model_id': 'minimax/h3-t2v',
                'provider': 'Crun AI',
                'duration_type': 'range',
                'allowed_durations': '4-15',
                'default_duration': 6,
                'supported_resolutions': '720p,1080p,4k',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('4.50'),
                'cost_1080p': Decimal('7.50'),
                'cost_4k': Decimal('14.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 13,
            },
            {
                'name': 'Hailuo 2.3 Artistic Motion',
                'model_id': 'hailuo/v2.3-t2v',
                'provider': 'Crun AI',
                'duration_type': 'discrete',
                'allowed_durations': '6,10',
                'default_duration': 6,
                'supported_resolutions': '720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.50'),
                'cost_720p': Decimal('4.00'),
                'cost_1080p': Decimal('7.00'),
                'cost_4k': Decimal('14.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 14,
            },
            {
                'name': 'Vidu Q3 Ultra',
                'model_id': 'vidu/q3-t2v',
                'provider': 'Crun AI',
                'duration_type': 'range',
                'allowed_durations': '4-16',
                'default_duration': 8,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('5.50'),
                'cost_4k': Decimal('11.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 15,
            },
            {
                'name': 'Vidu Q2',
                'model_id': 'vidu/q2-t2v',
                'provider': 'Crun AI',
                'duration_type': 'discrete',
                'allowed_durations': '5,10',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.20'),
                'cost_720p': Decimal('2.50'),
                'cost_1080p': Decimal('4.50'),
                'cost_4k': Decimal('9.00'),
                'allowed_wallet': 'standard',
                'is_active': True,
                'is_default': False,
                'sort_order': 16,
            },
            {
                'name': 'PixVerse V6',
                'model_id': 'pixverse/v6-t2v',
                'provider': 'Crun AI',
                'duration_type': 'discrete',
                'allowed_durations': '5,8,15',
                'default_duration': 5,
                'supported_resolutions': '480p,720p,1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('1.50'),
                'cost_720p': Decimal('3.00'),
                'cost_1080p': Decimal('5.00'),
                'cost_4k': Decimal('10.00'),
                'allowed_wallet': 'standard',
                'is_active': True,
                'is_default': False,
                'sort_order': 17,
            },
            {
                'name': 'Alibaba HappyHorse 1.1',
                'model_id': 'alibaba/happyhorse-1.1-t2v',
                'provider': 'Crun AI',
                'duration_type': 'range',
                'allowed_durations': '3-15',
                'default_duration': 5,
                'supported_resolutions': '1080p',
                'pricing_type': 'per_second',
                'cost_480p': Decimal('2.00'),
                'cost_720p': Decimal('3.50'),
                'cost_1080p': Decimal('6.00'),
                'cost_4k': Decimal('12.00'),
                'allowed_wallet': 'both',
                'is_active': True,
                'is_default': False,
                'sort_order': 18,
            },
        ]

        count = 0
        for item in models_data:
            m_id = item.pop('model_id')
            obj, created = TextToVideoModelConfig.objects.update_or_create(
                model_id=m_id,
                defaults=item
            )
            count += 1

        self.stdout.write(self.style.SUCCESS(f"Successfully seeded {count} official Crun AI Text-to-Video models!"))
